/**
 * text-utils.ts — Tiện ích text dùng chung cho CLIENT (bundle trình duyệt).
 *
 * Ràng buộc (giữ nguyên khi sửa file này):
 * - PHẢI pure: KHÔNG import bất kỳ module node-only nào (fs/path/crypto/pg...).
 *   Nếu cần crypto thì tách sang src/lib/ai-core.ts (chỉ dùng ở server).
 * - Chuyển NGUYÊN VĂN từ MarkdownRenderer.tsx, không sửa logic.
 */

/**
 * Preprocesses content to normalize LaTeX math and fix degree/coordinate notation
 * such as $23^\circ 23'B$ (Geography 12), temperature $25^\circ C$, and angle degrees.
 * Strictly prevents normal Vietnamese text and units from being corrupted by LaTeX.
 */
export function preprocessMathContent(content: string): string {
  if (!content) return '';

  let text = content;

  // 1. Clean up any stray \text{...} around Vietnamese words that may have been generated by earlier bugs or AI
  text = text.replace(
    /\\text\{([àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđĐA-Za-z0-9\s.,'°%_\-—/]+)\}/g,
    '$1'
  );

  // 2. Fix decomposed accents that KaTeX / TeX sometimes produces, e.g. "n a ˘ m" -> "năm", "a ˘" -> "ă"
  text = text.replace(/n\s*a\s*˘\s*m/gi, 'năm');
  text = text.replace(/a\s*˘/gi, 'ă');

  // 3. Convert standard LaTeX display and inline delimiters \[ ... \] and \( ... \) to $$ and $
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, '$$$$1$$$');
  text = text.replace(/\\\(([\s\S]*?)\\\)/g, '$$$1$$');

  // 4. Fix Vietnamese Geographic coordinates with degrees and minutes
  // Examples in Địa lí 12: $23^\circ 23'B$, 23^\circ 23'B, $102^\circ 09'Đ$, $8^\circ 34'B$, $109^\circ 28'Đ$
  text = text.replace(
    /\$?\b(\d{1,3})\s*(?:\^\\circ|\\circ|\\degree|°)\s*(\d{1,2})?\s*(?:'|′|’)?\s*([BNDTEWbndte]|Đ|đ)\b\$?/g,
    (_, deg, min, dir) => {
      const direction = dir.toUpperCase();
      const minutes = min ? `${min}'` : '';
      return `${deg}°${minutes}${direction}`;
    }
  );

  // 5. Fix temperature degrees like 25^\circ C, $25^\circ C$, 100^\circ C
  text = text.replace(
    /\$?\b(\d+(?:[.,]\d+)?)\s*(?:\^\\circ|\\circ|\\degree)\s*([CcFf])\b\$?/g,
    '$1°$2'
  );

  // 6. Fix loose degree notation like: "góc 60^\circ", "từ 0^\circ đến 90^\circ"
  text = text.replace(/(\d+(?:[.,]\d+)?)\s*\^\\circ\b/g, '$1°');

  // 7. Clean up single degree inside $...$ like $23^\circ$ or $90^\circ$ outside complex equations
  text = text.replace(/\$(\d+(?:[.,]\d+)?)\s*(?:\^\\circ|\\circ|\\degree)\$/g, '$1°');

  // 8. Fix common units and stats wrapped erroneously in $...$ (like $1500 - 2000 mm/năm$, $> 80%$)
  text = text.replace(
    /\$(\s*[><=~±]?\s*[\d\s.,-]+(?:mm|cm|m|km|km²|km2|m³|m3|kg|g|tấn|héc-ta|ha|%|người|triệu|tỉ|tỷ|USD|đồng|độ|mm\/năm|mm\/nam)[^$]*)\$/gi,
    '$1'
  );

  // 9. If an inline $...$ contains prose with Vietnamese accented words, it is NOT math! Strip the $ delimiters.
  text = text.replace(/\$([^\n$]+)\$/g, (match, inner) => {
    // Check if inner contains multiple Vietnamese accented words or common Vietnamese words
    const vietnameseWordMatches = inner.match(
      /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđĐ]/gi
    );
    // If it has 2 or more accented characters and contains spaces/prose, it's text, not math
    if (vietnameseWordMatches && vietnameseWordMatches.length >= 2 && /\s/.test(inner)) {
      // Check if it's a real math formula like $f(x) = \text{với } x > 0$
      if (!/[\\=+\-_^*/∫∑√≤≥≠]/.test(inner)) {
        return inner; // return clean text without dollar signs
      }
    }
    return match;
  });

  return text;
}
